name: Publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Python environment
        uses: actions/setup-python@v2
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install
      - name: Test
        run: pipenv run test
        env:
          ROBINHOOD_DEVICE_TOKEN: ${{ secrets.ROBINHOOD_DEVICE_TOKEN }}
          ROBINHOOD_USERNAME: ${{ secrets.ROBINHOOD_USERNAME }}
          ROBINHOOD_PASSWORD: ${{ secrets.ROBINHOOD_PASSWORD }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Python environment
        uses: actions/setup-python@v2
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install dev dependencies
        run: pipenv install --dev
      - name: Bump version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          pipenv run bump
          git push
      - name: Build
        run: pipenv run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  publish:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Python environment
        uses: actions/setup-python@v2
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install dev dependencies
        run: pipenv install --dev
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
