name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Python environment
        uses: actions/setup-python@v2
      - name: Install Pipenv
        run: pip install pipenv
      - name: Test
        run: pipenv run test
